### ISSUE TITLE
按你这样设置了，没翻译

### ISSUE THREAD

**Issue by bhtomming** [chen4w/ra-language-chinese#6]
都按你这样设置了，但没有显示翻译
import React from "react";
import { Redirect, Route } from "react-router-dom";
import { HydraAdmin, hydraDataProvider as baseHydraDataProvider, fetchHydra as baseFetchHydra, ResourceGuesser, FieldGuesser } from "@api-platform/admin";
import parseHydraDocumentation from "@api-platform/api-doc-parser/lib/hydra/parseHydraDocumentation";
import authProvider from "./authProvider";
import chineseMessages from 'ra-language-chinese';
import dashboard from "./Dashboard";
import BookList from "./Components/BookList";

const entrypoint = process.env.REACT_APP_API_ENTRYPOINT;
const fetchHeaders = { Authorization: `Bearer ${window.localStorage.getItem("token")}` };
const fetchHydra = (url, options = {}) => baseFetchHydra(url, {
    ...options,
    headers: new Headers(fetchHeaders),
});
const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint, { headers: new Headers(fetchHeaders) })
    .then(
        ({ api }) => ({ api }),
        (result) => {
            switch (result.status) {
                case 401:
                    return Promise.resolve({
                        api: result.api,
                        customRoutes: [
                            <Route path="/" render={() => {
                                if(new Date().getTime() > parseInt(window.localStorage.getItem("express")) + parseInt(window.localStorage.getItem('startTime')))
                                {
                                    window.localStorage.removeItem("token");
                                }
                                return window.localStorage.getItem("token") ? window.location.reload() : <Redirect to="/login" />
                            }} />
                        ],
                    });
                default:
                    return Promise.reject(result);
            }
        },
    );
const dataProvider = baseHydraDataProvider(entrypoint, fetchHydra, apiDocumentationParser);

const messages = {
    'cn': chineseMessages
};

export default () => (
    <HydraAdmin
        locale="cn"
        messages={ messages }
        dashboard={ dashboard }
        dataProvider={ dataProvider }
        authProvider={ authProvider }
        entrypoint={ entrypoint }
    >
    <ResourceGuesser name={"books"}  source={"books"} List={BookList}  />

    </HydraAdmin>
);

我使用的是api-admin这个组件是在react-admin基础之上改装的，里面的设置应该不变。

**Comment by chen4w** [comment]
更新了翻译
